# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c190cb64881765dae1e5efa84ff342992b861e098b62826a1dc317989c5762e173b5e474da05076828ef309c18f620179bed15e68634c9e88a040a3997a06f

test:
  secret_key_base: 2e1e87349b05568092f58b3ae97b2288d316c383aa258966fa195fd15a0078461a053aa6d6a8607b1fc73ff8adeef9e75366ffdce10350e65010caf4d3b67493

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
